# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipments.EquipmentType'),
        ),
    ]
