# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20170801_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Area')),
            ],
            options={
                'verbose_name': 'EquipmentArea',
                'verbose_name_plural': 'EquipmentAreas',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'IN'), ('W', 'WASTED'), ('T', 'TRANSFER')], default='I', max_length=1)),
                ('quantity', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField()),
                ('equipment_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.EquipmentArea')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='area',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_wasted',
        ),
        migrations.AddField(
            model_name='equipmentarea',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment'),
        ),
    ]
