# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20170804_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
