# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20170804_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='equipment_area',
        ),
        migrations.AddField(
            model_name='operation',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment'),
            preserve_default=False,
        ),
    ]
