# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_operation_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.Area'),
        ),
    ]
