# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_operation_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAreaIdle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_quantity', models.IntegerField(default=0)),
                ('equipment_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.EquipmentArea')),
            ],
            options={
                'verbose_name': 'EquipmentAreaIdle',
                'verbose_name_plural': 'EquipmentAreaIdles',
            },
        ),
    ]
