# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('questions', '0002_auto_20170527_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('destination_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_equipment_id', to='equipments.Equipment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('source_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_equipment_id', to='equipments.Equipment')),
            ],
        ),
    ]
