# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20170804_0046'),
        ('questions', '0003_requestdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdetail',
            name='source_equipment',
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='source_equipmentarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_equipment_id', to='equipments.EquipmentArea'),
            preserve_default=False,
        ),
    ]
