# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
