# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
