# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170807_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
