# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20170814_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d'),
        ),
    ]
